<?php

class Bailarin extends Persona
{
    public function __construct(string $nombre, string $fechaNacimiento, string $direccion, private string $estilo)
    {
        parent::__construct($nombre, $fechaNacimiento, $direccion);
    }
    public function __toString()
    {
        return parent::__toString()." y es ".__CLASS__." con estilo especializado en ".$this->getEstilo(); // TODO: Change the autogenerated stub
    }
    public function getEstilo(): string{
        return $this->estilo;
    }
}


?>