<?php

class Medico extends Persona
{
    use Asalariado;
    public function __construct(string $nombre, string $fechaNacimiento, string $direccion, private string $especialidad,float $salario)
    {
        parent::__construct($nombre, $fechaNacimiento, $direccion);
        $this->setSalario($salario);
    }
    public function __toString()
    {
        return parent::__toString()." y es ".__CLASS__." especializado en ".$this->getEspecialidad(); // TODO: Change the autogenerated stub
    }
    public function getEspecialidad(): string{
        return $this->especialidad;
    }
}


?>